services:
  fineract:
    image: ${IMAGE_NAME:-fineract:latest}
    volumes:
      - ${PWD}/config/docker/logback/logback-override.xml:/app/logback-override.xml
      - ${PWD}/config/docker/aws/etc/credentials:/etc/aws/credentials:ro
      - ${PWD}/build/fineract/logs:/var/logs/fineract:rw
      - ${PWD}/build/fineract/content:/opt/fineract/.fineract:rw

    environment:
      FINERACT_CONTENT_DIRECTORY: "/opt/fineract/.fineract"

    healthcheck:
      test: ["CMD", "sh", "-c", "echo -e \"Checking for the availability of Fineract server deployment\"; while ! nc -z \"localhost\" 8443; do sleep 1; printf \"-\"; done; echo -e \" >> Fineract server has started\";"]
      timeout: 1s
      retries: 60
